// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"github.com/mtavano/ghreviews"
)

type GhReviewsEvent struct {
	Total      int                   `json:"total"`
	NewReviews []*ghreviews.GhReview `json:"newReviews"`
}
